// منصة السبتاني — 100 تحدي محلول.
#import "report-theme.typ": report-accent, report-theme
#show: report-theme.with(title: "100 تحدي برمجي مع الحلول", author: "المهندس محمد عادل السبتاني", rhythm: "report", running-header: true)
#set text(font: "Noto Sans Arabic", lang: "ar", size: 8.7pt)
#set par(leading: .8em, spacing: .55em)
#page(margin: (top: 28%, x: 2.2cm), numbering: none, header: none)[#align(center)[#text(size: 27pt, weight: "bold", fill: report-accent)[100 تحدي برمجي مع الحلول]#v(.6em)#text(size: 14pt)[Python • HTML/CSS • C++]#v(2em)#text(size: 11pt)[منصة السبتاني — إعداد المهندس محمد عادل السبتاني]]]
#page(numbering: none, header: none)[#outline(title: [الفهرس], indent: 1.5em)]
#counter(page).update(1)

= كيف تتدرب
اقرأ التحدي، وحاول حله خلال عشر دقائق، ثم قارن بفكرة الحل. الحلول قصيرة عمداً؛ حسّنها باختبارات للحواف، ورسائل أوضح، وأسماء معبّرة.

= Python — 34 تحدياً
#enum(start: 1)[
اطبع اسمك. الحل: `print("محمد")`. اجمع رقمين. الحل: `a,b=4,6; print(a+b)`. افحص الزوجية. الحل: `n % 2 == 0`. اعكس كلمة. الحل: `word[::-1]`. أوجد أكبر رقم. الحل: `max(values)`. أوجد المجموع. الحل: `sum(values)`. عد الكلمات. الحل: `len(text.split())`. صفّ الأعداد الزوجية. الحل: `[n for n in nums if n%2==0]`. أنشئ قاموس طالب. الحل: `{"name":"ليان","points":0}`. زد نقاطاً آمنة. الحل: `user["points"]=user.get("points",0)+10`. اكتب دالة مربع. الحل: `def square(n): return n*n`. أعد قيمة افتراضية. الحل: `value or "غير محدد"`. اطبع 1 إلى 5. الحل: `for n in range(1,6): print(n)`. اجمع حتى n. الحل: `sum(range(n+1))`. احسب طول كلمات. الحل: `[len(w) for w in words]`. التقط رقماً غير صالح. الحل: `try: n=int(x) except ValueError: n=0`. اقرأ ملف UTF-8. الحل: `Path("a.txt").read_text(encoding="utf-8")`. اكتب ملفاً. الحل: `Path("a.txt").write_text(text,encoding="utf-8")`. حوّل قاموساً إلى JSON. الحل: `json.dumps(data,ensure_ascii=False)`. اقرأ JSON. الحل: `json.loads(raw)`. أعد مفتاحاً آمناً. الحل: `data.get("title","بلا عنوان")`. احسب تكرار حروف. الحل: `Counter(text)`. اجمع حسب فئة. الحل: `totals[k]=totals.get(k,0)+v`. رتّب درجات. الحل: `sorted(scores,reverse=True)`. أنشئ صنف Course. الحل: `class Course: pass`. اكتب تمثيلاً نصياً. الحل: `def __str__(self): return self.title`. تحقّق من شبكة. الحل: `timeout=5`. افحص نجاح HTTP. الحل: `200 <= status < 300`. اعرض بطاقة API. الحل: استخرج `title` و`source` بقيم بديلة. أعد المحاولة. الحل: حلقة محدودة مع تأخير للقراءات فقط. استخدم enumerate. الحل: `for i,item in enumerate(items,1)`. اختبر قائمة فارغة. الحل: `if not values:return 0`. أضف type hint. الحل: `def total(values:list[int])->int:`. اكتب اختباراً. الحل: `assert square(3)==9`.
]

= HTML وCSS — 33 تحدياً
#enum(start: 35)[
أنشئ صفحة عربية. الحل: `<html lang="ar" dir="rtl">`. أضف عنواناً رئيسياً. الحل: `<h1>منصة السبتاني</h1>`. أضف فقرة وصف. الحل: `<p>تعلم بالتطبيق</p>`. أضف رابطاً آمناً. الحل: `target="_blank" rel="noreferrer"`. صف صورة. الحل: `alt="وصف مفيد"`. أنشئ نموذج بريد. الحل: `<input type="email" required>`. اربط label. الحل: `for="email"` و`id="email"`. أنشئ جدولاً دلالياً. الحل: `table`, `thead`, `th`, `tbody`. أضف زر إرسال. الحل: `<button type="submit">إرسال</button>`. فعّل border-box. الحل: `*{box-sizing:border-box}`. عرف لون علامة. الحل: `:root{--brand:#f26722}`. استعمل متغير اللون. الحل: `color:var(--brand)`. أنشئ بطاقة. الحل: `padding`, `border`, `background`. نسق ابناً مباشراً. الحل: `.card > h2`. رتب صفاً. الحل: `display:flex; gap:1rem`. اسمح بالالتفاف. الحل: `flex-wrap:wrap`. وسّط عمودياً. الحل: `align-items:center`. أنشئ Grid متكيفاً. الحل: `repeat(auto-fit,minmax(15rem,1fr))`. اجعل عنواناً مرناً. الحل: `font-size:clamp(2rem,6vw,5rem)`. أضف media query. الحل: `@media(min-width:48rem){...}`. أظهر تركيزاً. الحل: `:focus-visible{outline:3px solid #f26722}`. أضف hover. الحل: `button:hover{transform:translateY(-2px)}`. احترم الحركة المخفضة. الحل: `prefers-reduced-motion`. اكتب شريط تقدم. الحل: `<progress value="4" max="10">`. أنشئ قائمة هاتف. الحل: بدّل صنف `open` بزر. حدّث aria-expanded. الحل: `button.setAttribute("aria-expanded",open)`. أخف القائمة على الهاتف. الحل: `display:none` ثم `.open{display:grid}`. اجعل الصورة مرنة. الحل: `img{max-width:100%;height:auto}`. استخدم مساحة قراءة. الحل: `max-width:70ch`. اصنع ظل سطح. الحل: `box-shadow:0 10px 30px #13203322`. أنشئ تدرجاً هادئاً. الحل: `linear-gradient(135deg,#fff8ed,#f4ead8)`. راجع التباين. الحل: نص داكن فوق خلفية فاتحة. اختبر Tab. الحل: تنقل دون فأرة واصلح الترتيب.
]

= C++ — 33 تحدياً
#enum(start: 68)[
اطبع Hello. الحل: `std::cout << "Hello\\n"`. اجمع رقمين. الحل: `int a=3,b=4; std::cout<<a+b`. افحص موجباً. الحل: `if(n>0)`. اكتب حلقة. الحل: `for(int i=0;i<5;++i)`. أنشئ vector. الحل: `std::vector<int> v{1,2,3}`. أضف عنصراً. الحل: `v.push_back(4)`. مر على العناصر. الحل: `for(int x:v)`. احسب مجموعاً. الحل: `std::accumulate(v.begin(),v.end(),0)`. أوجد أكبر قيمة. الحل: `std::max_element(v.begin(),v.end())`. مرر بالمرجع. الحل: `void add(int& x){++x;}`. مرر للقراءة. الحل: `const std::string& name`. افحص pointer. الحل: `if(ptr != nullptr)`. أنشئ unique_ptr. الحل: `std::make_unique<int>(7)`. أنشئ صنفاً. الحل: `class User{public:int points=0;};`. اجعل الحالة خاصة. الحل: ضع المتغير قبل `public:`. اكتب getter ثابتاً. الحل: `int get() const`. افتح ملفاً. الحل: `std::ifstream in("a.txt")`. اكتب ملفاً. الحل: `std::ofstream out("a.txt")`. افحص الملف. الحل: `if(!out) throw std::runtime_error("open")`. اكتب قالب دالة. الحل: `template<class T>T id(T x){return x;}`. اكتب قالب صنف. الحل: `template<class T>class Box{T value;};`. ارمِ استثناءً. الحل: `throw std::invalid_argument("bad")`. التقط استثناء. الحل: `catch(const std::exception& e)`. امنع قسمة صفرية. الحل: افحص المقام قبل القسمة. طبق RAII. الحل: اجعل الملف كائناً محلياً. استخدم at. الحل: `v.at(index)`. عرف constexpr. الحل: `constexpr int limit=100`. استخدم enum class. الحل: `enum class Level{Beginner,Advanced};`. اكتب switch. الحل: `switch(level){case Level::Beginner:...}`. أعد نتيجة صريحة. الحل: لا تخفِ الأخطاء في قيمة سحرية. فعّل تحذيرات. الحل: `-Wall -Wextra`. اختبر حافة فارغة. الحل: `if(v.empty()) return;`. سمّ المتغيرات. الحل: `student_count` بدلاً من `x`.
]

== خاتمة
الحل الأول ليس النهاية. أعد كتابة كل تحدٍ بطريقتك، ثم أضف حالة حدّية واختباراً صغيراً قبل الانتقال إلى التالي.
